//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookLibrary_WCFService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookDataContract", Namespace="http://schemas.datacontract.org/2004/07/BookLibrary_WCFService")]
    public partial class BookDataContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private bool IsAvailableField;
        
        private string TitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable
        {
            get
            {
                return this.IsAvailableField;
            }
            set
            {
                this.IsAvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveBookResult", Namespace="http://schemas.datacontract.org/2004/07/BookLibrary_WCFService")]
    public partial class SaveBookResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsCompletedField;
        
        private int NewIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCompleted
        {
            get
            {
                return this.IsCompletedField;
            }
            set
            {
                this.IsCompletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewId
        {
            get
            {
                return this.NewIdField;
            }
            set
            {
                this.NewIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteBookResult", Namespace="http://schemas.datacontract.org/2004/07/BookLibrary_WCFService")]
    public partial class DeleteBookResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DeletedIdField;
        
        private string DeletedTitleField;
        
        private bool IsDeletedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeletedId
        {
            get
            {
                return this.DeletedIdField;
            }
            set
            {
                this.DeletedIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeletedTitle
        {
            get
            {
                return this.DeletedTitleField;
            }
            set
            {
                this.DeletedTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/BookLibrary_WCFService")]
    public partial class BookFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ILibraryService")]
public interface ILibraryService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetBookById", ReplyAction="http://tempuri.org/ILibraryService/GetBookByIdResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(BookLibrary_WCFService.BookFault), Action="http://tempuri.org/ILibraryService/GetBookByIdBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/BookLibrary_WCFService")]
    BookLibrary_WCFService.BookDataContract GetBookById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetBookById", ReplyAction="http://tempuri.org/ILibraryService/GetBookByIdResponse")]
    System.Threading.Tasks.Task<BookLibrary_WCFService.BookDataContract> GetBookByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/AddBook", ReplyAction="http://tempuri.org/ILibraryService/AddBookResponse")]
    BookLibrary_WCFService.SaveBookResult AddBook(BookLibrary_WCFService.BookDataContract book);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/AddBook", ReplyAction="http://tempuri.org/ILibraryService/AddBookResponse")]
    System.Threading.Tasks.Task<BookLibrary_WCFService.SaveBookResult> AddBookAsync(BookLibrary_WCFService.BookDataContract book);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/RemoveBook", ReplyAction="http://tempuri.org/ILibraryService/RemoveBookResponse")]
    BookLibrary_WCFService.DeleteBookResult RemoveBook(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/RemoveBook", ReplyAction="http://tempuri.org/ILibraryService/RemoveBookResponse")]
    System.Threading.Tasks.Task<BookLibrary_WCFService.DeleteBookResult> RemoveBookAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/UpdateBook", ReplyAction="http://tempuri.org/ILibraryService/UpdateBookResponse")]
    bool UpdateBook(BookLibrary_WCFService.BookDataContract book);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/UpdateBook", ReplyAction="http://tempuri.org/ILibraryService/UpdateBookResponse")]
    System.Threading.Tasks.Task<bool> UpdateBookAsync(BookLibrary_WCFService.BookDataContract book);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/DownloadBookFile", ReplyAction="http://tempuri.org/ILibraryService/DownloadBookFileResponse")]
    System.IO.Stream DownloadBookFile(int bookId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/DownloadBookFile", ReplyAction="http://tempuri.org/ILibraryService/DownloadBookFileResponse")]
    System.Threading.Tasks.Task<System.IO.Stream> DownloadBookFileAsync(int bookId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILibraryServiceChannel : ILibraryService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LibraryServiceClient : System.ServiceModel.ClientBase<ILibraryService>, ILibraryService
{
    
    public LibraryServiceClient()
    {
    }
    
    public LibraryServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LibraryServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LibraryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LibraryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public BookLibrary_WCFService.BookDataContract GetBookById(int id)
    {
        return base.Channel.GetBookById(id);
    }
    
    public System.Threading.Tasks.Task<BookLibrary_WCFService.BookDataContract> GetBookByIdAsync(int id)
    {
        return base.Channel.GetBookByIdAsync(id);
    }
    
    public BookLibrary_WCFService.SaveBookResult AddBook(BookLibrary_WCFService.BookDataContract book)
    {
        return base.Channel.AddBook(book);
    }
    
    public System.Threading.Tasks.Task<BookLibrary_WCFService.SaveBookResult> AddBookAsync(BookLibrary_WCFService.BookDataContract book)
    {
        return base.Channel.AddBookAsync(book);
    }
    
    public BookLibrary_WCFService.DeleteBookResult RemoveBook(int id)
    {
        return base.Channel.RemoveBook(id);
    }
    
    public System.Threading.Tasks.Task<BookLibrary_WCFService.DeleteBookResult> RemoveBookAsync(int id)
    {
        return base.Channel.RemoveBookAsync(id);
    }
    
    public bool UpdateBook(BookLibrary_WCFService.BookDataContract book)
    {
        return base.Channel.UpdateBook(book);
    }
    
    public System.Threading.Tasks.Task<bool> UpdateBookAsync(BookLibrary_WCFService.BookDataContract book)
    {
        return base.Channel.UpdateBookAsync(book);
    }
    
    public System.IO.Stream DownloadBookFile(int bookId)
    {
        return base.Channel.DownloadBookFile(bookId);
    }
    
    public System.Threading.Tasks.Task<System.IO.Stream> DownloadBookFileAsync(int bookId)
    {
        return base.Channel.DownloadBookFileAsync(bookId);
    }
}
