using BookLibrary_WCFService.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Runtime.Serialization;
using CoreWCF;
using System.Text;
using Microsoft.EntityFrameworkCore;

namespace BookLibrary_WCFService
{
    // NOTE: You can use the "Rename" command on the "Refactor" menu to change the class name "ILibraryService" in code, svc and config file together.
    // NOTE: In order to launch WCF Test Client for testing this service, please select ILibraryService.svc or ILibraryService.svc.cs at the Solution Explorer and start debugging.
    
    public class LibraryService : ILibraryService
    {
        private string connectionString = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=BookRepository";
        private LibraryDbContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor; // 1. Inject HttpContext Accessor

        public LibraryService(LibraryDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }

        public async Task<BookDataContract> GetBookByIdAsync(int id)
        {
            // 2. Safely retrieve the real request abortion token generated by Kestrel
            CancellationToken cancellationToken = _httpContextAccessor.HttpContext?.RequestAborted
                                                  ?? CancellationToken.None;

            var book = await _context.Books.FirstOrDefaultAsync(b => b.Id == id, cancellationToken);

            if (book == null)
            {
                var fault = new BookFault { ErrorMessage = $"Book with ID {id} was not found." };
                throw new FaultException<BookFault>(fault, new FaultReason("Invalid book ID"));
            }

            var bookDataContract = new BookDataContract() { Id = book.Id, Title = book.Title, IsAvailable = book.IsAvailable };
            return bookDataContract;
        }

        public async Task<SaveBookResult> AddBookAsync(BookDataContract book)
        {
            var databaseModel = new Book()
            {
                Id = book.Id,
                Title = book.Title,
                IsAvailable = book.IsAvailable
            };

            await _context.Books.AddAsync(databaseModel);
            int rowsChanged = await _context.SaveChangesAsync();
            var output = (rowsChanged > 0);
            var newId = databaseModel.Id;
            return new SaveBookResult { IsCompleted = output, NewId = newId };
        }

        public async Task<DeleteBookResult> RemoveBookAsync(int id)
        {
            var bookToRemove = await _context.Books.FirstOrDefaultAsync(b => b.Id == id);

            if (bookToRemove == null)
            {
                var fault = new BookFault { ErrorMessage = $"Book with ID {id} was not found." };
                throw new FaultException<BookFault>(fault, new FaultReason("Invalid Book Id"));
            }

            _context.Books.Remove(bookToRemove);
            bool isDeleted = await _context.SaveChangesAsync() > 0;
            return new DeleteBookResult { DeletedId = id, DeletedTitle = bookToRemove.Title, IsDeleted = isDeleted };
        }

        public async Task<bool> UpdateBookAsync(BookDataContract book)
        {
            var bookToUpdate = await _context.Books.FirstOrDefaultAsync(b => b.Id == book.Id);

            if (bookToUpdate == null)
            {
                var fault = new BookFault { ErrorMessage = $"Book with ID {book.Id} was not found." };
                throw new FaultException<BookFault>(fault, new FaultReason("Invalid Book Id"));
            }

            bookToUpdate.Title = book.Title;
            bookToUpdate.IsAvailable = book.IsAvailable;
            var rowsChanged = await _context.SaveChangesAsync();
            return rowsChanged > 0;
        }

        public async Task<Stream> DownloadBookFileAsync(int bookId)
        {
            CancellationToken cancellationToken = _httpContextAccessor.HttpContext?.RequestAborted
                                              ?? CancellationToken.None;

            cancellationToken.ThrowIfCancellationRequested(); // Drop out early if client aborted instantly

            // Define your physical file storage path
            string filePath = $@"C:\LibraryAssets\book_{bookId}.pdf";

            if (!File.Exists(filePath))
            {
                var fault = new BookFault { ErrorMessage = $"File for book ID {bookId} does not exist." };
                throw new FaultException<BookFault>(fault, new FaultReason("Asset Not Found"));
            }

            // Open the stream with useAsync: true to yield threads during disk reads
            return new FileStream(
                filePath,
                FileMode.Open,
                FileAccess.Read,
                FileShare.Read,
                bufferSize: 4096,
                useAsync: true
            );
        }
    }
}
